# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/guides/building-and-testing-python

name: Pyspice Test

# Trigger the workflow on
on:
  push:
    branches:
      - master
      - devel
  pull_request:
    branches:
      - master
  # page_build:
  # release:
  #   types: # This configuration does not affect the page_build event above
  #     - created

# A map of environment variables
env:
  # SERVER: production

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
defaults:
  run:
    shell: bash
#     working-directory: scripts

jobs:
  install-test:
    name: Install and Test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # python-version: [3.8, 3.9]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install beautifulsoup4 invoke requests
        pip3 install pytest
        pip3 install pyterate
        pip3 install pint

    - name: Install PySpice
      run: pip3 install .

    - name: Run Unit-Tests
      run: pytest unit-test

    - name: Test on Windows
      if: matrix.os == 'windows-latest'
        run: |
          pyspice-post-installation --install-ngspice-dll
          pyspice-post-installation --check-install
          export PYTHONIOENCODING="utf_8"
          invoke test.run-examples
